# Generated by Django 3.2.8 on 2021-10-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211008_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrequest',
            old_name='user_id',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='followrequest',
            old_name='target_user_id',
            new_name='following',
        ),
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('follower', 'following')},
        ),
    ]
